#学习到pandans操作  
1、多列相同值取最大值进行合并  
2、one-hot编码  
3、通过值Serises值进行索引DataFrame

In [243]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
import numpy as np

In [244]:
#数据加载
basket = pd.read_csv('../../datasets/MarketBasket/Market_Basket_Optimisation.csv', 
                    header=None)

In [245]:
basket.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7501 entries, 0 to 7500
Data columns (total 20 columns):
0     7501 non-null object
1     5747 non-null object
2     4389 non-null object
3     3345 non-null object
4     2529 non-null object
5     1864 non-null object
6     1369 non-null object
7     981 non-null object
8     654 non-null object
9     395 non-null object
10    256 non-null object
11    154 non-null object
12    87 non-null object
13    47 non-null object
14    25 non-null object
15    8 non-null object
16    4 non-null object
17    4 non-null object
18    3 non-null object
19    1 non-null object
dtypes: object(20)
memory usage: 1.1+ MB

In [246]:
basket.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [247]:
pd.Series.str.get?

## 采用efficient_apriori进行频繁项集挖掘

In [248]:
#把所有不为空的列值进行合并
columns_item = basket.apply(lambda x: list(x.dropna()), axis=1)

In [249]:
columns_item.head()

0    [shrimp, almonds, avocado, vegetables mix, gre...
1                           [burgers, meatballs, eggs]
2                                            [chutney]
3                                    [turkey, avocado]
4    [mineral water, milk, energy bar, whole wheat ...
dtype: object

In [250]:
#把原数据编程transaction的形式
transaction_data = list(columns_item)
len(transaction_data)

7501

In [251]:
#查看有多少不同的商品

#把所有list数组进行合并,找到不重复的列
len(np.unique(np.concatenate(transaction_data)))

120

In [252]:
#采用efficient_apriori 工具包
from efficient_apriori import apriori

In [253]:
itemsets1, rules1 = apriori(transaction_data, min_support=0.02,  min_confidence=0.05)

In [254]:
len(rules1)

100

In [255]:
rules1

[{eggs} -> {burgers},
 {burgers} -> {eggs},
 {french fries} -> {burgers},
 {burgers} -> {french fries},
 {mineral water} -> {burgers},
 {burgers} -> {mineral water},
 {spaghetti} -> {burgers},
 {burgers} -> {spaghetti},
 {mineral water} -> {cake},
 {cake} -> {mineral water},
 {mineral water} -> {chicken},
 {chicken} -> {mineral water},
 {eggs} -> {chocolate},
 {chocolate} -> {eggs},
 {french fries} -> {chocolate},
 {chocolate} -> {french fries},
 {frozen vegetables} -> {chocolate},
 {chocolate} -> {frozen vegetables},
 {green tea} -> {chocolate},
 {chocolate} -> {green tea},
 {ground beef} -> {chocolate},
 {chocolate} -> {ground beef},
 {milk} -> {chocolate},
 {chocolate} -> {milk},
 {mineral water} -> {chocolate},
 {chocolate} -> {mineral water},
 {spaghetti} -> {chocolate},
 {chocolate} -> {spaghetti},
 {mineral water} -> {cooking oil},
 {cooking oil} -> {mineral water},
 {french fries} -> {eggs},
 {eggs} -> {french fries},
 {frozen vegetables} -> {eggs},
 {eggs} -> {frozen vegetables},
 {green tea} -> {eggs},
 {eggs} -> {green tea},
 {milk} -> {eggs},
 {eggs} -> {milk},
 {mineral water} -> {eggs},
 {eggs} -> {mineral water},
 {pancakes} -> {eggs},
 {eggs} -> {pancakes},
 {spaghetti} -> {eggs},
 {eggs} -> {spaghetti},
 {green tea} -> {french fries},
 {french fries} -> {green tea},
 {milk} -> {french fries},
 {french fries} -> {milk},
 {mineral water} -> {french fries},
 {french fries} -> {mineral water},
 {pancakes} -> {french fries},
 {french fries} -> {pancakes},
 {spaghetti} -> {french fries},
 {french fries} -> {spaghetti},
 {mineral water} -> {frozen smoothie},
 {frozen smoothie} -> {mineral water},
 {milk} -> {frozen vegetables},
 {frozen vegetables} -> {milk},
 {mineral water} -> {frozen vegetables},
 {frozen vegetables} -> {mineral water},
 {spaghetti} -> {frozen vegetables},
 {frozen vegetables} -> {spaghetti},
 {mineral water} -> {green tea},
 {green tea} -> {mineral water},
 {spaghetti} -> {green tea},
 {green tea} -> {spaghetti},
 {milk} -> {ground beef},
 {ground beef} -> {milk},
 {mineral water} -> {ground beef},
 {ground beef} -> {mineral water},
 {spaghetti} -> {ground beef},
 {ground beef} -> {spaghetti},
 {mineral water} -> {low fat yogurt},
 {low fat yogurt} -> {mineral water},
 {mineral water} -> {milk},
 {milk} -> {mineral water},
 {spaghetti} -> {milk},
 {milk} -> {spaghetti},
 {olive oil} -> {mineral water},
 {mineral water} -> {olive oil},
 {pancakes} -> {mineral water},
 {mineral water} -> {pancakes},
 {shrimp} -> {mineral water},
 {mineral water} -> {shrimp},
 {soup} -> {mineral water},
 {mineral water} -> {soup},
 {spaghetti} -> {mineral water},
 {mineral water} -> {spaghetti},
 {tomatoes} -> {mineral water},
 {mineral water} -> {tomatoes},
 {whole wheat rice} -> {mineral water},
 {mineral water} -> {whole wheat rice},
 {spaghetti} -> {olive oil},
 {olive oil} -> {spaghetti},
 {spaghetti} -> {pancakes},
 {pancakes} -> {spaghetti},
 {spaghetti} -> {shrimp},
 {shrimp} -> {spaghetti},
 {tomatoes} -> {spaghetti},
 {spaghetti} -> {tomatoes}]

## 用mlxtend.frequent_patterns进行频繁项集挖掘

In [256]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
pd.options.display.max_columns=100

In [257]:
#转化为one-hot编码
basket_hot_encoding = pd.get_dummies(basket, prefix='', prefix_sep='')

In [258]:
len(basket_hot_encoding.columns)

1269

In [259]:
basket_hot_encoding.columns.unique()

Index(['almonds', 'antioxydant juice', 'asparagus', 'avocado', 'babies food',
       'bacon', 'barbecue sauce', 'black tea', 'blueberries', 'body spray',
       ...
       'whole weat flour', 'whole wheat pasta', 'whole wheat rice', 'yams',
       'yogurt cake', 'tea', 'water spray', 'zucchini', 'napkins',
       ' asparagus'],
      dtype='object', length=120)

In [260]:
#找到napkis列值为1 的行。
gg = basket_hot_encoding['napkins']
gg[gg.max(axis=1).isin([1])]

      napkins  napkins  napkins  napkins
871         0        1        0        0
2961        0        0        1        0
3116        0        1        0        0
3658        1        0        0        0
7177        0        0        0        1

In [261]:
gg.groupby(level=0, axis=1).max(axis =1)

      napkins
0           0
1           0
2           0
3           0
4           0
...       ...
7496        0
7497        0
7498        0
7499        0
7500        0

[7501 rows x 1 columns]

In [262]:
#列名有1269维，去重复后120维，所以要对数据进行处理
#相同的列名的数值取最大值，并合并成一列
basket_hot_encoding_unique = basket_hot_encoding.groupby(level=0, axis= 1).max(axis = 1)

In [263]:
#检查
basket_hot_encoding_unique.head()

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,body spray,bramble,brownies,bug spray,burger sauce,burgers,butter,cake,candy bars,carrots,cauliflower,cereals,champagne,chicken,chili,chocolate,chocolate bread,chutney,cider,clothes accessories,cookies,cooking oil,corn,cottage cheese,cream,dessert wine,eggplant,eggs,energy bar,energy drink,escalope,extra dark chocolate,flax seed,french fries,french wine,fresh bread,fresh tuna,fromage blanc,frozen smoothie,frozen vegetables,...,melons,milk,mineral water,mint,mint green tea,muffins,mushroom cream sauce,napkins,nonfat milk,oatmeal,oil,olive oil,pancakes,parmesan cheese,pasta,pepper,pet food,pickles,protein bar,red wine,rice,salad,salmon,salt,sandwich,shallot,shampoo,shrimp,soda,soup,spaghetti,sparkling water,spinach,strawberries,strong cheese,tea,tomato juice,tomato sauce,tomatoes,toothpaste,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [264]:
basket_hot_encoding_unique.columns

Index([' asparagus', 'almonds', 'antioxydant juice', 'asparagus', 'avocado',
       'babies food', 'bacon', 'barbecue sauce', 'black tea', 'blueberries',
       ...
       'turkey', 'vegetables mix', 'water spray', 'white wine',
       'whole weat flour', 'whole wheat pasta', 'whole wheat rice', 'yams',
       'yogurt cake', 'zucchini'],
      dtype='object', length=120)

In [110]:
#将数据标准化
def encode_units(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1
basket_hot_encoding = basket_hot_encoding.applymap(encode_units)

In [265]:
#挖掘频繁项集与关联规则
frequent_itemsets = apriori(basket_hot_encoding_unique, min_support=0.02, use_colnames=True)
rules2 = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.05)

In [266]:
rules2

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(burgers),(eggs),0.087188,0.179709,0.028796,0.330275,1.837830,0.013128,1.224818
1,(eggs),(burgers),0.179709,0.087188,0.028796,0.160237,1.837830,0.013128,1.086988
2,(burgers),(french fries),0.087188,0.170911,0.021997,0.252294,1.476173,0.007096,1.108844
3,(french fries),(burgers),0.170911,0.087188,0.021997,0.128705,1.476173,0.007096,1.047650
4,(mineral water),(burgers),0.238368,0.087188,0.024397,0.102349,1.173883,0.003614,1.016889
...,...,...,...,...,...,...,...,...,...
95,(spaghetti),(pancakes),0.174110,0.095054,0.025197,0.144717,1.522468,0.008647,1.058066
96,(spaghetti),(shrimp),0.174110,0.071457,0.021197,0.121746,1.703760,0.008756,1.057260
97,(shrimp),(spaghetti),0.071457,0.174110,0.021197,0.296642,1.703760,0.008756,1.174209
98,(tomatoes),(spaghetti),0.068391,0.174110,0.020931,0.306043,1.757755,0.009023,1.190117
99,(spaghetti),(tomatoes),0.174110,0.068391,0.020931,0.120214,1.757755,0.009023,1.058905

In [267]:
print("频繁项集：", frequent_itemsets)
print("关联规则：", rules2[ (rules2['lift'] >= 1) & (rules2['confidence'] >= 0.05) ])

频繁项集：       support                           itemsets
0    0.020397                          (almonds)
1    0.033329                          (avocado)
2    0.033729                         (brownies)
3    0.087188                          (burgers)
4    0.030129                           (butter)
..        ...                                ...
98   0.020131  (mineral water, whole wheat rice)
99   0.022930             (olive oil, spaghetti)
100  0.025197              (pancakes, spaghetti)
101  0.021197                (spaghetti, shrimp)
102  0.020931              (tomatoes, spaghetti)

[103 rows x 2 columns]
关联规则：         antecedents     consequents  antecedent support  consequent support  \
0         (burgers)          (eggs)            0.087188            0.179709
1            (eggs)       (burgers)            0.179709            0.087188
2         (burgers)  (french fries)            0.087188            0.170911
3    (french fries)       (burgers)            0.170911            0.087188
4   (mineral water)       (burgers)            0.238368            0.087188
..              ...             ...                 ...                 ...
95      (spaghetti)      (pancakes)            0.174110            0.095054
96      (spaghetti)        (shrimp)            0.174110            0.071457
97         (shrimp)     (spaghetti)            0.071457            0.174110
98       (tomatoes)     (spaghetti)            0.068391            0.174110
99      (spaghetti)      (tomatoes)            0.174110            0.068391

     support  confidence      lift  leverage  conviction
0   0.028796    0.330275  1.837830  0.013128    1.224818
1   0.028796    0.160237  1.837830  0.013128    1.086988
2   0.021997    0.252294  1.476173  0.007096    1.108844
3   0.021997    0.128705  1.476173  0.007096    1.047650
4   0.024397    0.102349  1.173883  0.003614    1.016889
..       ...         ...       ...       ...         ...
95  0.025197    0.144717  1.522468  0.008647    1.058066
96  0.021197    0.121746  1.703760  0.008756    1.057260
97  0.021197    0.296642  1.703760  0.008756    1.174209
98  0.020931    0.306043  1.757755  0.009023    1.190117
99  0.020931    0.120214  1.757755  0.009023    1.058905

[94 rows x 9 columns]